### ISSUE TITLE
Conversion from DFA to NFA does not properly handle state names of mixed data types

### ISSUE THREAD

**Issue by colette-b** [caleb531/automata#60] opened 2022-10-02 00:27 UTC
I found the following bug:
nfa._add_new_state introduces integers into the set of states.

Current code is:
```
    def _add_new_state(state_set, start=0):
        """Adds new state to the state set and returns it"""
        new_state = start
        while new_state in state_set:
            new_state += 1

        state_set.add(new_state)

        return new_state
```
which could be fixed, for example, in this way:
```
    def _add_new_state(state_set, start=0):
        """Adds new state to the state set and returns it"""
        new_state = start
        while str(new_state) in state_set:
            new_state += 1

        state_set.add(str(new_state))

        return str(new_state)
```
EDIT: this bugfix actually runs into other problems later - this is just an idea
_____________________
This can lead to logic problems later. For example the following code fails:
```
from automata.fa.dfa import DFA
from automata.fa.nfa import NFA

A = NFA(
    states={'0', '1'},
    input_symbols={'0'},
    transitions={'0': {'0': {'1'}}, '1': {'0': {'1'}}},
    initial_state='0',
    final_states={'1'}
)

print(A.reverse().states)

B = DFA.from_nfa(A.reverse())

assert(A.accepts_input('00')==B.accepts_input('00'))
```

**Comment by caleb531** [comment] 2022-10-06 20:35
@colette-b Hm, I see your point, although I have intentionally added official support for non-string states over the past few releases of the library.

I was also able to fix your example by using pure integers for the state names instead of numeric strings. Note that the input symbols can remain as strings:

```py
from automata.fa.dfa import DFA
from automata.fa.nfa import NFA

A = NFA(
    states={0, 1},
    input_symbols={'0'},
    transitions={0: {'0': {1}}, 1: {'0': {1}}},
    initial_state=0,
    final_states={1}
)

print(A.reverse().states)

B = DFA.from_nfa(A.reverse())

assert(A.accepts_input('00')==B.accepts_input('00'))
```

**Comment by caleb531** [comment] 2022-10-06 20:45
@colette-b Good news! I was actually able to refactor `_add_new_state` to correctly handle non-string states, thus fixing your original example. All other automated tests are passing too, so there should be no regressions from this refactor.

In case you're curious, here is the new implementation:

```python
@staticmethod
def _add_new_state(state_set, start=0):
    """Adds new state to the state set and returns it"""
    new_state = start
    str_state_set = {str(state) for state in state_set}
    while str(new_state) in str_state_set:
        new_state += 1

    state_set.add(new_state)

    return new_state
```

**Comment by eliotwrobson** [comment] 2022-10-08 22:26
@caleb531 Looking at this, won't there be a similar issue whenever an NFA contains both string and integer states? I think it has to do with the fact that the `from_nfa` function uses strings as state names.

**Comment by caleb531** [comment] 2022-10-08 22:28
@eliotwrobson Possibly, but with the above fix I've implemented, all tests are still passing, including [this new test I added that specifically addresses state names of mixed types](https://github.com/caleb531/automata/blob/develop/tests/test_nfa.py#L491).

**Comment by eliotwrobson** [comment] 2022-10-09 00:16
@caleb531 It looks like the test you wrote checks for the fact that the `_add_new_state` now has better support for integer string state names, but there are still issues when manually constructing an NFA.

The following (somewhat contrived) assertion fails:
```python
A = NFA(
    states={1, '1'},
    input_symbols={'0'},
    transitions={1: {'0': {'1'}}, '1': {'0': {'1'}}},
    initial_state=1,
    final_states={'1'}
)

B = DFA.from_nfa(A)

assert A.accepts_input('00') == B.accepts_input('00')

**Comment by caleb531** [comment] 2022-10-09 00:33
@eliotwrobson Thank you for the (contrived) example, actually! With it, I can verify that there is a larger issue here.

Let me play around with the code and see what I can come up with for a solution.

**Comment by eliotwrobson** [comment] 2022-10-09 00:39
@caleb531 Sounds good! I fixed this issue in our local version of the library by making changes to `from_nfa` to handle the internal states differently, our implementation is here:
```python
def from_nfa(cls: Type[DFA], target_nfa: nfa.NFA, retain_names: bool = True) -> DFA:
        """Initialize this DFA as one equivalent to the given NFA."""
        dfa_states: Set[DFAStateT] = set()
        dfa_symbols = target_nfa.input_symbols
        dfa_transitions: DFATransitionsT = {}

        # Data structures for state renaming
        new_state_name_dict: Dict[Tuple[DFAStateT, ...], int] = dict()
        state_name_counter = 0
        def get_name_renamed(states: Set[DFAStateT]) -> DFAStateT:
            nonlocal state_name_counter, new_state_name_dict
            canonical_form_states = cls._to_canonical_form(states)

            if canonical_form_states in new_state_name_dict:
                return new_state_name_dict[canonical_form_states]

            new_state_name_dict[canonical_form_states] = state_name_counter
            state_name_counter += 1
            return state_name_counter-1

        def get_name_original(states: Set[DFAStateT]) -> DFAStateT:
            return cls._to_canonical_form(states)

        get_name = get_name_original if retain_names else get_name_renamed

        # equivalent DFA states states
        nfa_initial_states = target_nfa._get_lambda_closure(target_nfa.initial_state)
        dfa_initial_state = get_name(nfa_initial_states)
        dfa_final_states: Set[DFAStateT] = set()

        state_queue: Deque[Set[DFAStateT]] = deque()
        state_queue.append(nfa_initial_states)
        while state_queue:
            current_states = state_queue.popleft()
            current_state_name: DFAStateT = get_name(current_states)
            if current_state_name in dfa_states:
                # We've been here before and nothing should have changed.
                continue


            # Add NFA states to DFA as it is constructed from NFA.
            dfa_states.add(current_state_name)
            dfa_transitions[current_state_name] = {}
            if (current_states & target_nfa.final_states):
                dfa_final_states.add(current_state_name)


            # Enqueue the next set of current states for the generated DFA.
            for input_symbol in target_nfa.input_symbols:
                next_current_states = target_nfa._get_next_current_states(
                    current_states, input_symbol)
                dfa_transitions[current_state_name][input_symbol] = get_name(next_current_states)
                state_queue.append(next_current_states)


        return cls(
            states=dfa_states, input_symbols=dfa_symbols,
            transitions=dfa_transitions, initial_state=dfa_initial_state,
            final_states=dfa_final_states)
```

Note that this required modifying some of your test cases to comply with the different state types.

**Comment by caleb531** [comment] 2022-10-09 03:35
So I took a stab at it. Definitely more complicated than I thought. My approach was something like the following:

```
@staticmethod
def _stringify_states(states, state_map, state_counter):
    """Adds new state to the state map and returns it"""
    hashable_states = frozenset(states)
    if hashable_states not in state_map:
        state_map[hashable_states] = state_counter
        state_counter += 1
    return state_map[hashable_states]

@classmethod
def from_nfa(cls, target_nfa):
    """Initialize this DFA as one equivalent to the given NFA."""
    dfa_states = set()
    dfa_symbols = target_nfa.input_symbols
    dfa_transitions = dict()
    state_map = {}
    state_counter = 0
```

I think the implementation _may_ be right, but it's kind of a chicken-and-egg problem because I have to modify the tests correctly to know for sure.

@eliotwrobson Since you already have this solved in your fork, would you be so kind as to submit me a PR with the new `DFA.from_nfa` implementation as well as the updated tests?

**Comment by eliotwrobson** [comment] 2022-10-09 03:41
@caleb531 Sure! Just a heads up that the function on my end changes the types of the states used (from strings of tuples to the tuples themselves), and the tests will reflect that. I'll put up the draft PR with the implementation ASAP (for greater visiblity), then update the tests on the draft.

**Comment by caleb531** [comment] 2022-11-15 23:27
Closing this ticket since the state names should now be handled correctly with the recent v7 release. Please let me know if this is still not the case, though. :)

**Closed by caleb531** 2022-11-15 23:27 UTC
Labels: bug
