### ISSUE TITLE
Bug: NFA doesn't support non-string states

### ISSUE THREAD

**Issue by jasonxia17** [caleb531/automata#21] opened 2021-01-15 23:52 UTC
```python
from automata.fa.nfa import NFA

nfa = NFA(
    states={0},
    input_symbols={'0'},
    transitions={0: {}},
    initial_state=0,
    final_states=set()
)

print(nfa.accepts_input(''))
```

I would expect this to print `False`, because the NFA has no accepting states. Instead, it throws this error:
```
File "/usr/local/lib/python3.8/site-packages/automata/base/automaton.py", line 41, in accepts_input
    self.read_input(input_str)
  File "/usr/local/lib/python3.8/site-packages/automata/base/automaton.py", line 34, in read_input
    for config in validation_generator:
  File "/usr/local/lib/python3.8/site-packages/automata/fa/nfa.py", line 120, in read_input_stepwise
    self._check_for_input_rejection(current_states)
  File "/usr/local/lib/python3.8/site-packages/automata/fa/nfa.py", line 104, in _check_for_input_rejection
    ', '.join(current_states)))
TypeError: sequence item 0: expected str instance, int found
```

Would it be possible to replace `', '.join(current_states)` with `', '.join(str(state) for state in current_states)`, or something along those lines?

**Comment by caleb531** [comment] 2021-01-23 22:24
@jasonxia17 Good call. I will fix this now and push up a new release for you to test within the next day or two.

**Comment by jasonxia17** [comment] 2021-01-23 23:08
Thank you! By the way, I think the same issue also occurs here: https://github.com/caleb531/automata/blob/1672cfc6f431c46ef207eaa8f3d1b9ee6181c8e0/automata/base/automaton.py#L65

If the user provides an invalid non-string final state, then they will get a confusing error message instead of the intended error message.

**Comment by caleb531** [comment] 2021-01-28 02:13
@jasonxia17 Good catch. I've just pushed 31fbe8f with the fix, and test for all automaton types in the library to validate the fix. But please test yourself and confirm things are good on your end before I push a release.

**Comment by caleb531** [comment] 2021-03-20 22:47
@jasonxia17 I think it's safe to close this issue since I am confident the new tests cover all cases for the bug. Thank you for reporting it!

**Closed** 2021-03-20 22:47 UTC
Labels: bug

**Comment by maryembenali** [comment] 2022-08-17 18:46
hey, is the library automata updated in relation with this error tho ( this one https://pypi.org/project/automata-lib/ )?

**Comment by caleb531** [comment] 2022-08-17 19:06
@maryembenali Yes, that was fixed in the NFA class for the v5 release currently on PyPI.

I am aware there is currently a similar issue with DFAs, but I already have that fixed and it will be part of the upcoming v6 release.

**Comment by maryembenali** [comment] 2022-08-17 20:38
alright , i just wanted to check , not too sure if it's related to this bug but i was wondering why would i keep getting this error with nfa :"automata.base.exceptions.InvalidStateError: end state q for transition on q0 is not valid" even tho there's no transition q in my  automata  while using " nfa.accepts_input(my_input_str)" ( my automata works in a seperate folder but not in my project one)

**Comment by caleb531** [comment] 2022-08-17 20:47
@maryembenali Yeah, I think you're describing a separate issue than this ticket. Can you please create a separate issue so I can look into it? Please include the NFA code you are using, if possible—anything that might help me reproduce the issue on my end.
