### ISSUE TITLE
(NFA)automata.base.exceptions.InvalidStateError: end state q for transition on q0 is not valid

### ISSUE THREAD

**Issue by maryembenali** [caleb531/automata#49] opened 2022-08-17 21:09 UTC
hey i ve getting this error while using "nfa.accepts_input(my_input_str)" in my project , i tried the same structure of the automata in a seperate file and it functionned properly , im wondering if anyone could guide me a little to figure out what to fix ( or at least the scenarios that may lead to this error thanks!
here's my project link
https://github.com/maryembenali/automata.git

```
automata.base.exceptions.InvalidStateError: end state q for transition on q0 is not valid
```

**Comment by caleb531** [comment] 2022-08-17 21:29
@maryembenali Okay, I have your Tkinter app up and running. Can you please provide me the field values you are using to test? I'm not sure what I should be entering on each of the screens.

<img width="690" alt="Screen Shot 2022-08-17 at 2 27 02 PM" src="https://user-images.githubusercontent.com/872474/185246438-d7ad7286-5a1d-4bcd-b182-b0afdc78ee68.png">
<img width="390" alt="Screen Shot 2022-08-17 at 2 27 26 PM" src="https://user-images.githubusercontent.com/872474/185246448-2e01b509-f05e-4be8-9b28-bb40df3fa540.png">

^ just the first two screens. If you could please provide the values that I should enter on all of the screens, that would be extremely helpful!

**Comment by maryembenali** [comment] 2022-08-17 21:41
@caleb531  
These are the inputs i tried to enter
- tick indeterministic (doesn't do anything for the moment)
- 2 
-    *a 
     *b
- 3
- {"q0": {"a": "q1"}, "q1": {"a": "q1", "b": "q2"},"q2": {"b": "q0"}}
- q0
- 1
-q1
Also i recommend to change the path of the image so it can be displayed properly
Thank u very much!

**Comment by caleb531** [comment] 2022-08-17 21:51
@maryembenali Perfect, I was able to reproduce the error. I'm pasting it here so I can reference it later:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/caleb/Desktop/automata-trial2/trial2.py", line 127, in Verify_Word
    nfa = NFA(states=set(States),input_symbols=set(Letters_List),transitions=Transitions_Dict,initial_state=Initial_state[0],final_states=set(final_states))
  File "/Users/caleb/Desktop/automata-trial2/.virtualenv/lib/python3.9/site-packages/automata/fa/nfa.py", line 21, in __init__
    self.validate()
  File "/Users/caleb/Desktop/automata-trial2/.virtualenv/lib/python3.9/site-packages/automata/fa/nfa.py", line 70, in validate
    self._validate_transition_end_states(start_state, paths)
  File "/Users/caleb/Desktop/automata-trial2/.virtualenv/lib/python3.9/site-packages/automata/fa/nfa.py", line 62, in _validate_transition_end_states
    raise exceptions.InvalidStateError(
automata.base.exceptions.InvalidStateError: end state q for transition on q0 is not valid
```

I will start debugging later today or tomorrow. I need to take a break right now.

**Comment by caleb531** [comment] 2022-08-17 23:34
@maryembenali Good news! I added some code to print out the NFA instance just before the error is thrown. I've pasted the output below:

```python
{
    "states": {"q1", "q2", "q0"},
    "input_symbols": {"b", "a"},
    "transitions": {"q0": {"a": "q1"}, "q1": {"a": "q1", "b": "q2"}, "q2": {"b": "q0"}},
    "initial_state": "q0",
    "final_states": {"q1"},
}
```

The immediate problem I can see is that the end states in your transition map are strings, which would work fine for a DFA. However, [per the documentation](https://github.com/caleb531/automata#class-nfafa), NFAs require that those inner-dict values be sets (since an NFA state can have transitions to multiple destination states for the same symbol).

In other words, your code should produce something like the following:

```python
{
    "states": {"q1", "q2", "q0"},
    "input_symbols": {"b", "a"},
    # notice {"a": {"q1"}} rather than {"a": "q1"}
    "transitions": {"q0": {"a": {"q1"}}, "q1": {"a": {"q1"}, "b": {"q2"}}, "q2": {"b": {"q0"}}},
    "initial_state": "q0",
    "final_states": {"q1"},
}
```

This totally explains the error you are seeing: `end state q ... is not valid` because the library is trying to iterate over the string value you currently provided, expecting that it's a set. The first element of a string is the first character, hence the lonely `q` rather than `q1`.

Given this, I will be closing this issue and marking it as _Invalid_, since it does not actually represent a bug in the Automata library itself. However, please feel free to continue posting in this thread with any questions you have.

**Closed by caleb531** 2022-08-17 23:34 UTC
Labels: bug

**Comment by maryembenali** [comment] 2022-08-18 12:08
@caleb531 thank you so much that was very helpful  ( i switched to this function ast.literal_eval(str) instead of json.loads(str)
